CREATE TABLE IF NOT EXISTS logging (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    description VARCHAR(256) NOT NULL,
    ip VARCHAR(16) NOT NULL,
    endpoint VARCHAR(256) NOT NULL,
    requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);